version: '3.8'

services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        container_name: mongodb
        volumes:
            - mongodb-data:/data/db
        networks:
            - mongo-network

volumes:
    mongodb-data:
networks:
    mongo-network:
